language: python
sudo: false
addons:
  apt:
    packages:
      - libgeoip-dev
      - python-lxml
      - python-psycopg2
      - python-yaml
  postgresql: "9.3"
python:
    - "2.7"
install:
  # - pip install -r test_requirements.txt
  # Set up Vagrant
  - sudo apt-get update -q
  - sudo apt-get install -y linux-headers-$(uname -r) virtualbox
  - wget https://releases.hashicorp.com/vagrant/1.9.8/vagrant_1.9.8_x86_64.deb
  - sudo dpkg -i vagrant_1.9.8_x86_64.deb
  - vagrant up
before_script:
  - psql -c 'create database oltest' -U postgres
  - PYTHONPATH=. python openlibrary/core/schema.py | psql -U postgres oltest
script: make test
